version: '3.8'
services:
  app:
    build: .
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3307/lootheaven?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
      - BASE_URL=http://213.139.208.110:8082
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password --port=3307
    ports:
      - "3307:3307"
    environment:
      - MYSQL_DATABASE=lootheaven
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - db-data:/var/lib/mysql
#      - /c/Users/sesa7/Desktop/lootheaven-server/backup.sql:/docker-entrypoint-initdb.d/backup.sql

volumes:
  db-data:
